### ISSUE TITLE
Use of Wire.requestFrom() and Wire.available()

### ISSUE THREAD

**Issue by Koepel** [bokunimowakaru/esp#1]
Hi, I noticed the many Wire.available() in the file "esp/2_example/example09_hum_sht31/i2c_sht31.ino". There is no reason to do that.

This code does the same:
 ```
        Wire.requestFrom(I2C_sht,6);
        if(Wire.available()!=6) return -999.0;
        temp = Wire.read();
        temp <<= 8;
        temp += Wire.read();
        Wire.read();
        hum = Wire.read();
        hum <<= 8;
        hum += Wire.read();
        // Wire.read()    // 6-th byte is not used
```

**Comment by bokunimowakaru** [comment]
It seems very nice, and I tried, but... it doesn't work on my ESP-WROOM-02.
I guess the ESP cannot recieved 6 bytes I2C data on the second line, "Wire.available".
So I think the waiting time for it should be adjusted to meet.
By the way, I also found the other issue for this example, and fixed it.

**Comment by Koepel** [comment]
The ESP does receive those 6 bytes, and the Wire.available() is not some kind of waiting function.

There are few differences between the Arduino Wire library and the ESP8266 Wire library. The [ESP8266 Wire.requestFrom()](https://github.com/esp8266/Arduino/blob/master/libraries/Wire/Wire.cpp) is however compatible and it waits until all bytes are received. The ESP8266 waits in the [twi_readfrom()](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_esp8266_si2c.c) function.

The Wire.available() function has a yield. I'm sure that all the extra Wire.available() is not needed for the I2C data, but you might need that yield for other code that is running.

It was not even a bug, I just noticed it. I suggest to keep it like this.

**Comment by bokunimowakaru** [comment]
Koepel, I committed to your code.
(I fonud it needs measuring time for the device.)
Thank you very much.
